In [146]:
import os
import sys
import json

import pandas as pd
import matplotlib.pyplot as plt

sys.path.append('../src')
from settings import YOUTUBE_DIR, TIMESTAMPS_DIR

In [2]:
with open(YOUTUBE_DIR / 'matches.jsonlines', 'r') as fin:
    lines = [json.loads(line) for line in fin]
df_matches = pd.DataFrame(lines)
df_matches['video_id'] = df_matches['video_url'].replace('https://www.youtube.com/watch\?v=', '', regex=True)
df_matches = df_matches.drop_duplicates()
df_matches = df_matches.sort_values('confidence', ascending=False)
df_matches[['match_id', 'video_id', 'radiant_name', 'dire_name', 'title', 'confidence']]

,match_id,video_id,radiant_name,dire_name,title,confidence
0,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,TALON vs POLARIS | ESL ONE MALAYSIA 2022,3
2,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,BOOM vs TALON | ESL ONE MALAYSIA 2022 SEA QUAL...,3
1,6678583793,r4rbY6zliTQ,Polaris Esports,T1,T1 vs POLARIS | ESL ONE MALAYSIA 2022 SEA QUAL...,2
3,6677043559,csurev0fmXI,BOOM Esports,Team SMG,BOOM vs SMG | ESL ONE MALAYSIA 2022 SEA QUALIF...,2
5,6676051545,cXA5Hw2boLA,Team Spirit,Team Secret,SECRET vs TEAM SPIRIT | RIYADH MASTERS 2022,2
7,6674755794,bzFzhRdT3cA,Royal Never Give Up,Team Spirit,TEAM SPIRIT vs RNG | RIYADH MASTERS 2022,2
9,6674755794,MANLkT4D0b8,Royal Never Give Up,Team Spirit,LIQUID vs RNG | RIYADH MASTERS 2022,2
4,6676393091,XTngObUROMo,PSG.LGD,Team Spirit,TEAM SPIRIT vs PSG LGD | RIYADH MASTERS 2022,1
6,6675726202,qIOA87h5Msc,PSG.LGD,OG,OG vs PSG LGD | RIYADH MASTERS 2022,1
8,6674445805,84XMNFPtL68,PSG.LGD,Nigma Galaxy,NIGMA vs PSG LGD | RIYADH MASTERS 2022,1

In [139]:
events = []
for file in os.listdir(TIMESTAMPS_DIR):
    if file == '.DS_Store':
        continue
    
    with open(TIMESTAMPS_DIR / file, 'r') as fin:
        video_id = file.split('.')[0]
        for line in fin:
            event = json.loads(line)
            event['video_id'] = video_id
            events.append(event)

df_timestamps = pd.DataFrame(events)

In [140]:
df_timestamps['int_frame_id'] = df_timestamps['frame_id'].astype(int)
df_timestamps.sort_values('int_frame_id', inplace=True)
df_timestamps = df_timestamps[pd.notnull(df_timestamps['timestamp'])].copy()
df_timestamps['timestamp'] = df_timestamps['timestamp'].astype(int)
df_timestamps

         video_id frame_id  text  timestamp  int_frame_id
3897  wUPhtY4sNP0      001  3.55        235             1
3898  wUPhtY4sNP0      002   355        235             2
3899  wUPhtY4sNP0      003  3.56        236             3
3900  wUPhtY4sNP0      004  3.57        237             4
3901  wUPhtY4sNP0      005  3.58        238             5
...           ...      ...   ...        ...           ...
3109  G4UcPjn7YFQ     2217  3317       1997          2217
3110  G4UcPjn7YFQ     2218  3317       1997          2218
3111  G4UcPjn7YFQ     2219  3317       1997          2219
3113  G4UcPjn7YFQ     2220  3317       1997          2220
3114  G4UcPjn7YFQ     2221  3317       1997          2221

[3819 rows x 5 columns]

In [152]:
df_timestamps['timestamp'].diff().describe()

count     3818.000000
mean         0.461498
std       1836.317649
min     -25168.000000
25%       -248.000000
50%          1.000000
75%        255.000000
max      24628.000000
Name: timestamp, dtype: float64

In [141]:
def dota_clock_format(seconds):
    minutes = str(seconds // 60).zfill(2)
    secs = str(seconds % 60).zfill(2)
    return f'{minutes}:{secs}'

In [142]:
from sklearn.cluster import DBSCAN

model = DBSCAN(eps=5, min_samples=5)
cluster = model.fit_predict(df_timestamps['timestamp'].to_numpy().reshape(-1, 1))
df_timestamps['cluster'] = cluster
df_timestamps['clock'] = df_timestamps['timestamp'].apply(dota_clock_format)

In [143]:
df_timestamps

         video_id frame_id  text  timestamp  int_frame_id  cluster  clock
3897  wUPhtY4sNP0      001  3.55        235             1        0  03:55
3898  wUPhtY4sNP0      002   355        235             2        0  03:55
3899  wUPhtY4sNP0      003  3.56        236             3        0  03:56
3900  wUPhtY4sNP0      004  3.57        237             4        0  03:57
3901  wUPhtY4sNP0      005  3.58        238             5        0  03:58
...           ...      ...   ...        ...           ...      ...    ...
3109  G4UcPjn7YFQ     2217  3317       1997          2217       12  33:17
3110  G4UcPjn7YFQ     2218  3317       1997          2218       12  33:17
3111  G4UcPjn7YFQ     2219  3317       1997          2219       12  33:17
3113  G4UcPjn7YFQ     2220  3317       1997          2220       12  33:17
3114  G4UcPjn7YFQ     2221  3317       1997          2221       12  33:17

[3819 rows x 7 columns]

In [144]:
df_timestamps[df_timestamps['cluster'] == -1]

         video_id frame_id    text  timestamp  int_frame_id  cluster   clock
923   ieh5x4uz-OE      252   21440      12880           252       -1  214:40
927   ieh5x4uz-OE      256     214        134           256       -1   02:14
3563  G4UcPjn7YFQ      666   11224       6744           666       -1  112:24
1385  ieh5x4uz-OE      714     216        136           714       -1   02:16
1405  ieh5x4uz-OE      734     214        134           734       -1   02:14
3753  G4UcPjn7YFQ      856     216        136           856       -1   02:16
226   ieh5x4uz-OE     1115   - 442       -282          1115       -1   -5:18
230   ieh5x4uz-OE     1119   11212       6732          1119       -1  112:12
233   ieh5x4uz-OE     1121   11814       7094          1121       -1  118:14
2030  G4UcPjn7YFQ     1236   41410      24850          1236       -1  414:10
2031  G4UcPjn7YFQ     1237   41811      25091          1237       -1  418:11
2032  G4UcPjn7YFQ     1238    4152       2512          1238       -1   41:52
2033  G4UcPjn7YFQ     1239    4183       2543          1239       -1   42:23
2035  G4UcPjn7YFQ     1240    4184       2544          1240       -1   42:24
2036  G4UcPjn7YFQ     1241    4145       2505          1241       -1   41:45
2057  G4UcPjn7YFQ     1260   42844      25724          1260       -1  428:44
2085  G4UcPjn7YFQ     1286   43810      26290          1286       -1  438:10
2164  G4UcPjn7YFQ     1358  -46.21      -2781          1358       -1  -47:39
2268  G4UcPjn7YFQ     1452    S015         15          1452       -1   00:15
2295  G4UcPjn7YFQ     1477   $1.28         88          1477       -1   01:28
2302  G4UcPjn7YFQ     1483    $134         94          1483       -1   01:34
2303  G4UcPjn7YFQ     1484    $135         95          1484       -1   01:35
2304  G4UcPjn7YFQ     1485   $1.36         96          1485       -1   01:36
2325  G4UcPjn7YFQ     1504   53.06       3186          1504       -1   53:06
665   ieh5x4uz-OE     1514   31414      18854          1514       -1  314:14
2598  G4UcPjn7YFQ     1752    -551       -351          1752       -1   -6:09
2766  G4UcPjn7YFQ     1905   11910       7150          1905       -1  119:10
2767  G4UcPjn7YFQ     1906   11810       7090          1906       -1  118:10

In [121]:
df_timestamps = df_timestamps[df_timestamps['cluster'] != -1].copy()

In [130]:
df_highlights = df_timestamps.groupby(['video_id', 'cluster']).agg({'clock': ['first', 'last']})
df_highlights.sort_values(['video_id', ('clock', 'first')])
df_highlights.reset_index(inplace=True)
df_highlights.columns = ['video_id', 'cluster', 'start', 'end']
df_highlights

       video_id  cluster   start     end
0   G4UcPjn7YFQ        0   03:27   03:52
1   G4UcPjn7YFQ        1   00:45   01:07
2   G4UcPjn7YFQ        2   07:34   08:34
3   G4UcPjn7YFQ        3   14:00   14:01
4   G4UcPjn7YFQ        4   09:52   10:23
5   G4UcPjn7YFQ        5   10:45   11:18
6   G4UcPjn7YFQ        6   17:54   20:38
7   G4UcPjn7YFQ        7   12:22   12:27
8   G4UcPjn7YFQ        8   21:22   24:30
9   G4UcPjn7YFQ        9   26:05   25:54
10  G4UcPjn7YFQ       10   27:05   27:20
11  G4UcPjn7YFQ       11   27:43   31:37
12  G4UcPjn7YFQ       12   31:50   33:17
13  G4UcPjn7YFQ       13   35:12   36:40
14  G4UcPjn7YFQ       14   04:52   05:17
15  G4UcPjn7YFQ       15   06:03   06:27
16  G4UcPjn7YFQ       16   15:16   15:38
17  G4UcPjn7YFQ       17  214:14  214:15
18  G4UcPjn7YFQ       18   16:22   16:29
19  G4UcPjn7YFQ       20  311:14  311:14
20  G4UcPjn7YFQ       21   38:38   39:26
21  G4UcPjn7YFQ       23   40:10   41:09
22  G4UcPjn7YFQ       24   41:16   41:32
23  G4UcPjn7YFQ       25   42:43   43:24
24  G4UcPjn7YFQ       26   43:54   44:40
25  G4UcPjn7YFQ       27   46:10   46:57
26  G4UcPjn7YFQ       28   49:00   49:43
27  G4UcPjn7YFQ       29   49:59   50:39
28  G4UcPjn7YFQ       30   51:29   51:33
29  G4UcPjn7YFQ       31   52:48   53:00
30  G4UcPjn7YFQ       32   02:49   03:07
31  G4UcPjn7YFQ       33   54:00   54:38
32  G4UcPjn7YFQ       34   56:01   56:45
33  G4UcPjn7YFQ       35   56:59   57:45
34  G4UcPjn7YFQ       36   58:35   59:14
35  ieh5x4uz-OE        0   03:17   04:00
36  ieh5x4uz-OE        1   00:41   01:09
37  ieh5x4uz-OE        2   08:47   09:07
38  ieh5x4uz-OE        3   14:07   14:33
39  ieh5x4uz-OE        4   09:45   10:06
40  ieh5x4uz-OE        5   11:03   11:31
41  ieh5x4uz-OE        6   17:33   20:18
42  ieh5x4uz-OE        7   12:22   12:24
43  ieh5x4uz-OE        8   21:20   23:40
44  ieh5x4uz-OE        9   25:12   26:54
45  ieh5x4uz-OE       10   27:22   27:27
46  ieh5x4uz-OE       11   29:28   31:43
47  ieh5x4uz-OE       12   32:03   34:02
48  ieh5x4uz-OE       13   35:06   35:56
49  ieh5x4uz-OE       14   04:13   04:44
50  ieh5x4uz-OE       16   15:24   15:35
51  ieh5x4uz-OE       17  214:13  214:18
52  ieh5x4uz-OE       18   16:03   16:53
53  ieh5x4uz-OE       19   24:58   25:04
54  ieh5x4uz-OE       20  311:10  311:18
55  ieh5x4uz-OE       22   12:33   13:03
56  wUPhtY4sNP0        0   03:55   04:04

In [136]:
df = pd.merge(
    df_matches[['match_id', 'video_id', 'radiant_name', 'dire_name', 'confidence']], 
    df_highlights, 
    on=['video_id']
)
df = df.sort_values(['match_id', 'start'])
df

,match_id,video_id,radiant_name,dire_name,confidence,cluster,start,end
36,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,1,00:41,01:09
35,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,0,03:17,04:00
49,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,14,04:13,04:44
37,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,2,08:47,09:07
39,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,4,09:45,10:06
40,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,5,11:03,11:31
42,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,7,12:22,12:24
55,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,22,12:33,13:03
38,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,3,14:07,14:33
50,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,16,15:24,15:35
52,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,18,16:03,16:53
41,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,6,17:33,20:18
51,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,17,214:13,214:18
43,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,8,21:20,23:40
53,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,19,24:58,25:04
44,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,9,25:12,26:54
45,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,10,27:22,27:27
46,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,11,29:28,31:43
54,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,20,311:10,311:18
47,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,12,32:03,34:02
48,6678365022,ieh5x4uz-OE,BOOM Esports,Talon,3,13,35:06,35:56
1,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,1,00:45,01:07
30,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,32,02:49,03:07
0,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,0,03:27,03:52
14,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,14,04:52,05:17
15,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,15,06:03,06:27
2,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,2,07:34,08:34
4,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,4,09:52,10:23
5,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,5,10:45,11:18
7,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,7,12:22,12:27
3,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,3,14:00,14:01
16,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,16,15:16,15:38
18,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,18,16:22,16:29
6,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,6,17:54,20:38
17,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,17,214:14,214:15
8,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,8,21:22,24:30
9,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,9,26:05,25:54
10,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,10,27:05,27:20
11,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,11,27:43,31:37
19,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,20,311:14,311:14
12,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,12,31:50,33:17
13,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,13,35:12,36:40
20,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,21,38:38,39:26
21,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,23,40:10,41:09
22,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,24,41:16,41:32
23,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,25,42:43,43:24
24,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,26,43:54,44:40
25,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,27,46:10,46:57
26,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,28,49:00,49:43
27,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,29,49:59,50:39
28,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,30,51:29,51:33
29,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,31,52:48,53:00
31,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,33,54:00,54:38
32,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,34,56:01,56:45
33,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,35,56:59,57:45
34,6679653510,G4UcPjn7YFQ,Talon,Polaris Esports,3,36,58:35,59:14

# TODO

- 1 video contains 2-3 matches